version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
    - 5.2.2
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.9
    - 1.4.0
    - 1.4.1
  - dependency-name: concurrently
    versions:
    - 6.0.0
    - 6.0.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: husky
    versions:
    - 5.1.3
    - 5.2.0
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
  - dependency-name: redux
    versions:
    - 4.0.5
